"""PipeWire SOFA/HRTF virtual-surround configuration management."""

from __future__ import annotations

import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import threading
import time

from .config import ConfigStore


class SpatialError(OSError):
    """Spatial audio could not be configured or started."""


SPATIAL_NODE_NAME = "hs80_spatial"
SPATIAL_SERVICE = "hs80-spatial.service"
SPATIAL_START_TIMEOUT = 8.0


def _quote_pipewire(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate_pipewire_config(sofa_file: Path, target_sink: str) -> str:
    """Generate an isolated PipeWire client configuration for 7.1 HRTF."""

    positions = (
        ("FL", 30.0, 0.0),
        ("FR", 330.0, 0.0),
        ("FC", 0.0, 0.0),
        ("LFE", 0.0, -60.0),
        ("RL", 150.0, 0.0),
        ("RR", 210.0, 0.0),
        ("SL", 90.0, 0.0),
        ("SR", 270.0, 0.0),
    )
    sofa = _quote_pipewire(str(sofa_file))
    target = _quote_pipewire(target_sink)

    nodes: list[str] = []
    links: list[str] = []
    inputs: list[str] = []
    for index, (channel, azimuth, elevation) in enumerate(positions, start=1):
        nodes.append(
            f'''                    {{
                        type = sofa
                        label = spatializer
                        name = sp{channel}
                        config = {{ filename = {sofa} gain = 0.25 }}
                        control = {{
                            "Azimuth" = {azimuth:.1f}
                            "Elevation" = {elevation:.1f}
                            "Radius" = 3.0
                        }}
                    }}'''
        )
        links.append(f'                    {{ output = "sp{channel}:Out L" input = "mixL:In {index}" }}')
        links.append(f'                    {{ output = "sp{channel}:Out R" input = "mixR:In {index}" }}')
        inputs.append(f'"sp{channel}:In"')

    node_text = "\n".join(nodes)
    link_text = "\n".join(links)
    input_text = " ".join(inputs)
    return f'''# Generated by hs80-control. Manual edits are overwritten.
context.properties = {{
    log.level = 0
    default.clock.rate = 48000
    default.clock.quantum = 256
}}

context.spa-libs = {{
    audio.convert.* = audioconvert/libspa-audioconvert
    support.* = support/libspa-support
}}

context.modules = [
    {{ name = libpipewire-module-rt flags = [ ifexists nofail ] }}
    {{ name = libpipewire-module-protocol-native }}
    {{ name = libpipewire-module-client-node }}
    {{ name = libpipewire-module-adapter }}
    {{ name = libpipewire-module-filter-chain
        args = {{
            node.description = "HS80 Spatial 7.1"
            media.name = "HS80 Spatial 7.1"
            filter.graph = {{
                nodes = [
{node_text}
                    {{ type = builtin label = mixer name = mixL }}
                    {{ type = builtin label = mixer name = mixR }}
                ]
                links = [
{link_text}
                ]
                inputs = [ {input_text} ]
                outputs = [ "mixL:Out" "mixR:Out" ]
            }}
            capture.props = {{
                node.name = "{SPATIAL_NODE_NAME}"
                node.nick = "HS80 Spatial 7.1"
                media.class = Audio/Sink
                audio.channels = 8
                audio.position = [ FL FR FC LFE RL RR SL SR ]
            }}
            playback.props = {{
                node.name = "hs80_spatial_output"
                node.passive = true
                node.linger = true
                node.dont-fallback = true
                stream.dont-remix = true
                target.object = {target}
                audio.channels = 2
                audio.position = [ FL FR ]
            }}
        }}
    }}
]
'''


class SpatialManager:
    def __init__(self, config: ConfigStore, config_path: Path | None = None) -> None:
        self.config = config
        self.config_path = config_path or config.path.parent / "pipewire.conf"
        self.sofa_path = self.config_path.parent / "hrtf.sofa"
        self._lock = threading.RLock()

    @staticmethod
    def plugin_available() -> bool:
        candidates = (
            Path("/usr/lib64/spa-0.2/filter-graph/libspa-filter-graph-plugin-sofa.so"),
            Path("/usr/lib/spa-0.2/filter-graph/libspa-filter-graph-plugin-sofa.so"),
        )
        return any(path.exists() for path in candidates)

    @staticmethod
    def find_hs80_sink() -> str:
        result = SpatialManager._run_checked(["pw-dump"], timeout=5)
        try:
            objects = json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise SpatialError("pw-dump returned invalid JSON") from exc
        if not isinstance(objects, list):
            raise SpatialError("pw-dump returned an invalid object list")

        candidates: set[str] = set()
        for item in objects:
            if not isinstance(item, dict):
                continue
            if item.get("type") != "PipeWire:Interface:Node":
                continue
            properties = item.get("info", {}).get("props", {})
            if not isinstance(properties, dict):
                continue
            if properties.get("media.class") != "Audio/Sink":
                continue
            components = str(properties.get("alsa.components", "")).lower()
            if "usb1b1c:0a6b" in components:
                name = properties.get("node.name")
                if isinstance(name, str) and name and name != SPATIAL_NODE_NAME:
                    candidates.add(name)

        if len(candidates) == 1:
            return next(iter(candidates))
        if not candidates:
            raise SpatialError("physical HS80 PipeWire sink was not found")
        names = ", ".join(sorted(candidates))
        raise SpatialError(f"multiple physical HS80 PipeWire sinks found: {names}")

    def configure(self, sofa_file: str | Path) -> Path:
        with self._lock:
            source = Path(sofa_file).expanduser().resolve()
            if not source.is_file() or source.suffix.lower() != ".sofa":
                raise SpatialError("select an existing .sofa HRTF file")

            # Reconfigure an already running unit even if its virtual sink is
            # temporarily missing.  `is_enabled()` deliberately reports
            # readiness, while this transaction must preserve process state.
            was_enabled = self._service_is_active()
            target = self.find_hs80_sink()
            content = generate_pipewire_config(self.sofa_path, target)
            old_config = self.config.snapshot()
            self._prepare_private_directory()

            staged_sofa: Path | None = None
            staged_config: Path | None = None
            sofa_backup: Path | None = None
            config_backup: Path | None = None
            committed = False
            try:
                staged_sofa = self._stage_copy(source, ".hrtf.new.")
                staged_config = self._stage_text(content, ".pipewire.new.")
                sofa_backup = self._backup(self.sofa_path, ".hrtf.old.")
                config_backup = self._backup(self.config_path, ".pipewire.old.")
                # From here on, any partial replace must be rolled back.
                committed = True
                os.replace(staged_sofa, self.sofa_path)
                os.replace(staged_config, self.config_path)
                self.config.update_spatial(sofa_file=str(self.sofa_path))

                if was_enabled:
                    self._enable_locked()
                return self.config_path
            except Exception as exc:
                rollback_errors: list[str] = []
                if committed:
                    try:
                        self._restore_backup(self.sofa_path, sofa_backup)
                    except OSError as rollback_exc:
                        rollback_errors.append(f"HRTF rollback failed: {rollback_exc}")
                    try:
                        self._restore_backup(self.config_path, config_backup)
                    except OSError as rollback_exc:
                        rollback_errors.append(f"PipeWire config rollback failed: {rollback_exc}")
                    try:
                        self.config.replace(old_config)
                    except Exception as rollback_exc:
                        rollback_errors.append(f"settings rollback failed: {rollback_exc}")
                    if was_enabled:
                        try:
                            self._enable_locked()
                        except Exception as rollback_exc:
                            rollback_errors.append(f"service rollback failed: {rollback_exc}")

                detail = str(exc) or type(exc).__name__
                if rollback_errors:
                    detail += "; " + "; ".join(rollback_errors)
                raise SpatialError(detail) from exc
            finally:
                for temporary in (
                    staged_sofa,
                    staged_config,
                    sofa_backup,
                    config_backup,
                ):
                    if temporary is not None:
                        try:
                            temporary.unlink()
                        except FileNotFoundError:
                            pass

    def _prepare_private_directory(self) -> None:
        self.config_path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
        os.chmod(self.config_path.parent, 0o700)

    def _stage_copy(self, source: Path, prefix: str) -> Path:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=prefix, dir=self.config_path.parent
        )
        temporary = Path(temporary_name)
        try:
            with os.fdopen(descriptor, "wb") as destination:
                with source.open("rb") as source_stream:
                    shutil.copyfileobj(source_stream, destination)
                destination.flush()
                os.fsync(destination.fileno())
            os.chmod(temporary, 0o600)
            return temporary
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise

    def _stage_text(self, content: str, prefix: str) -> Path:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=prefix, dir=self.config_path.parent, text=True
        )
        temporary = Path(temporary_name)
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
                stream.write(content)
                stream.flush()
                os.fsync(stream.fileno())
            os.chmod(temporary, 0o600)
            return temporary
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise

    def _backup(self, path: Path, prefix: str) -> Path | None:
        if not path.exists():
            return None
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=prefix, dir=self.config_path.parent
        )
        os.close(descriptor)
        temporary = Path(temporary_name)
        try:
            shutil.copy2(path, temporary)
            return temporary
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise

    @staticmethod
    def _restore_backup(path: Path, backup: Path | None) -> None:
        if backup is None:
            path.unlink(missing_ok=True)
            return
        os.replace(backup, path)

    def _import_sofa(self, source: Path) -> Path:
        self._prepare_private_directory()
        if source == self.sofa_path.resolve(strict=False):
            return self.sofa_path

        descriptor, temporary_name = tempfile.mkstemp(
            prefix=".hrtf.", dir=self.config_path.parent
        )
        try:
            with os.fdopen(descriptor, "wb") as destination:
                with source.open("rb") as source_stream:
                    shutil.copyfileobj(source_stream, destination)
                destination.flush()
                os.fsync(destination.fileno())
            os.chmod(temporary_name, 0o600)
            os.replace(temporary_name, self.sofa_path)
        finally:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass
        return self.sofa_path

    def _write_configuration(self, sofa: Path) -> None:
        if not sofa.is_file() or sofa.suffix.lower() != ".sofa":
            raise SpatialError("configured .sofa HRTF file is missing")
        target = self.find_hs80_sink()
        content = generate_pipewire_config(sofa, target)
        self._prepare_private_directory()
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=".pipewire.", dir=self.config_path.parent, text=True
        )
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
                stream.write(content)
                stream.flush()
                os.fsync(stream.fileno())
            os.chmod(temporary_name, 0o600)
            os.replace(temporary_name, self.config_path)
        finally:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass

    @staticmethod
    def _run_checked(
        arguments: list[str], timeout: float = 10.0
    ) -> subprocess.CompletedProcess[str]:
        try:
            result = subprocess.run(
                arguments,
                check=False,
                text=True,
                capture_output=True,
                timeout=timeout,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise SpatialError(f"could not run {arguments[0]}: {exc}") from exc
        if result.returncode != 0:
            detail = result.stderr.strip() or result.stdout.strip() or "command failed"
            raise SpatialError(
                f"{arguments[0]} exited with status {result.returncode}: {detail}"
            )
        return result

    @classmethod
    def _systemctl(
        cls, *arguments: str, timeout: float = 10.0
    ) -> subprocess.CompletedProcess[str]:
        return cls._run_checked(
            ["systemctl", "--user", *arguments], timeout=timeout
        )

    @classmethod
    def _service_state(cls, timeout: float = 3.0) -> tuple[str, str]:
        result = cls._systemctl(
            "show",
            SPATIAL_SERVICE,
            "--property=LoadState",
            "--property=ActiveState",
            timeout=timeout,
        )
        properties: dict[str, str] = {}
        for line in result.stdout.splitlines():
            key, separator, value = line.partition("=")
            if separator:
                properties[key] = value
        if "LoadState" not in properties or "ActiveState" not in properties:
            raise SpatialError("systemctl returned incomplete service state")
        return properties["LoadState"], properties["ActiveState"]

    def is_enabled(self) -> bool:
        _load_state, active_state = self._service_state()
        if active_state != "active":
            return False
        # An active systemd unit only proves that the PipeWire client process
        # exists.  Expose Spatial as ready after its virtual sink is visible.
        return SPATIAL_NODE_NAME in self._pipewire_nodes(timeout=2.0)

    def _service_is_active(self) -> bool:
        _load_state, active_state = self._service_state()
        return active_state == "active"

    def set_enabled(self, enabled: bool) -> bool:
        with self._lock:
            return self._enable_locked() if enabled else self._disable_locked()

    def _enable_locked(self) -> bool:
        if not self.plugin_available():
            raise SpatialError(
                "SOFA support is missing; install pipewire-module-filter-chain-sofa"
            )

        load_state, active_state = self._service_state()
        if load_state == "not-found":
            raise SpatialError(f"{SPATIAL_SERVICE} is not installed")

        settings = self.config.snapshot()["spatial"]
        sofa_file = settings["sofa_file"]
        if not sofa_file:
            raise SpatialError("configure a .sofa HRTF file first")
        sofa = Path(sofa_file).expanduser().resolve()
        self._write_configuration(sofa)

        make_default = settings["make_default"]
        previous = settings["previous_default"] if make_default else ""
        if make_default and not previous:
            previous = self._default_sink_name()
            if previous == SPATIAL_NODE_NAME:
                raise SpatialError("cannot determine the default sink used before spatial audio")

        # This marker is persisted before changing systemd or WirePlumber so a
        # later disable can recover even if activation is interrupted.
        self.config.update_spatial(
            enabled=False,
            previous_default=previous,
        )

        deadline = time.monotonic() + SPATIAL_START_TIMEOUT
        try:
            if active_state == "active":
                self._systemctl(
                    "restart",
                    SPATIAL_SERVICE,
                    timeout=self._remaining(deadline, 5.0),
                )
            else:
                self._systemctl(
                    "enable",
                    "--now",
                    SPATIAL_SERVICE,
                    timeout=self._remaining(deadline, 5.0),
                )

            spatial_id = self._wait_for_sink(SPATIAL_NODE_NAME, deadline)
            if make_default:
                self._set_default(spatial_id, deadline)
                self._wait_for_default(SPATIAL_NODE_NAME, deadline)
            self.config.update_spatial(enabled=True)
            return True
        except Exception as exc:
            cleanup_errors: list[str] = []
            restored = not previous
            cleanup_deadline = time.monotonic() + 8.0
            if previous:
                try:
                    self._restore_previous(previous, cleanup_deadline)
                    restored = True
                except Exception as cleanup_exc:
                    cleanup_errors.append(f"default restore failed: {cleanup_exc}")
            try:
                self._stop_service(cleanup_deadline)
            except Exception as cleanup_exc:
                cleanup_errors.append(f"service stop failed: {cleanup_exc}")
            try:
                self.config.update_spatial(
                    enabled=False,
                    previous_default="" if restored else previous,
                )
            except Exception as cleanup_exc:
                cleanup_errors.append(f"state save failed: {cleanup_exc}")

            detail = str(exc) or type(exc).__name__
            if cleanup_errors:
                detail += "; " + "; ".join(cleanup_errors)
            raise SpatialError(detail) from exc

    def _disable_locked(self) -> bool:
        previous = self.config.snapshot()["spatial"]["previous_default"]
        errors: list[str] = []
        restored = not previous
        deadline = time.monotonic() + 8.0
        if previous:
            try:
                self._restore_previous(previous, deadline)
                restored = True
            except Exception as exc:
                errors.append(f"default restore failed: {exc}")

        try:
            self._stop_service(deadline)
        except Exception as exc:
            errors.append(f"service stop failed: {exc}")

        try:
            self.config.update_spatial(
                enabled=False,
                previous_default="" if restored else previous,
            )
        except Exception as exc:
            errors.append(f"state save failed: {exc}")

        if errors:
            raise SpatialError("; ".join(errors))
        return True

    def _stop_service(self, deadline: float | None = None) -> None:
        stop_deadline = deadline or time.monotonic() + 5.0
        load_state, active_state = self._service_state(
            self._remaining(stop_deadline, 1.0)
        )
        if load_state == "not-found":
            return
        if active_state == "inactive":
            self._systemctl(
                "disable",
                SPATIAL_SERVICE,
                timeout=self._remaining(stop_deadline, 4.0),
            )
        else:
            self._systemctl(
                "disable",
                "--now",
                SPATIAL_SERVICE,
                timeout=self._remaining(stop_deadline, 4.0),
            )

    @staticmethod
    def _remaining(deadline: float, maximum: float = 3.0) -> float:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise SpatialError("timed out waiting for PipeWire")
        return min(maximum, remaining)

    @classmethod
    def _default_sink_name(cls, timeout: float = 3.0) -> str:
        result = cls._run_checked(
            ["wpctl", "inspect", "@DEFAULT_AUDIO_SINK@"], timeout=timeout
        )
        for line in result.stdout.splitlines():
            match = re.search(r'node\.name\s*=\s*("(?:[^"\\]|\\.)*")\s*$', line)
            if match is None:
                continue
            try:
                name = json.loads(match.group(1))
            except json.JSONDecodeError as exc:
                raise SpatialError("wpctl returned an invalid default sink name") from exc
            if isinstance(name, str) and name:
                return name
        raise SpatialError("wpctl did not report the default sink name")

    @classmethod
    def _pipewire_nodes(cls, timeout: float) -> dict[str, str]:
        result = cls._run_checked(["pw-dump"], timeout=timeout)
        try:
            objects = json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise SpatialError("pw-dump returned invalid JSON") from exc
        if not isinstance(objects, list):
            raise SpatialError("pw-dump returned an invalid object list")

        nodes: dict[str, str] = {}
        for item in objects:
            if not isinstance(item, dict) or item.get("type") != "PipeWire:Interface:Node":
                continue
            properties = item.get("info", {}).get("props", {})
            if not isinstance(properties, dict) or properties.get("media.class") != "Audio/Sink":
                continue
            name = properties.get("node.name")
            node_id = item.get("id")
            if isinstance(name, str) and isinstance(node_id, (int, str)):
                nodes[name] = str(node_id)
        return nodes

    @classmethod
    def _wait_for_sink(cls, name: str, deadline: float) -> str:
        while True:
            nodes = cls._pipewire_nodes(cls._remaining(deadline, 1.0))
            if name in nodes:
                return nodes[name]
            _load_state, active_state = cls._service_state(
                cls._remaining(deadline, 1.0)
            )
            if active_state in {"failed", "inactive", "deactivating"}:
                raise SpatialError(
                    f"{SPATIAL_SERVICE} became {active_state} before its sink was ready"
                )
            time.sleep(min(0.1, cls._remaining(deadline, 0.1)))

    @classmethod
    def _set_default(cls, node_id: str, deadline: float) -> None:
        cls._run_checked(
            ["wpctl", "set-default", node_id],
            timeout=cls._remaining(deadline),
        )

    @classmethod
    def _wait_for_default(cls, name: str, deadline: float) -> None:
        while True:
            current = cls._default_sink_name(cls._remaining(deadline, 1.0))
            if current == name:
                return
            time.sleep(min(0.1, cls._remaining(deadline, 0.1)))

    @classmethod
    def _restore_previous(cls, previous: str, deadline: float) -> None:
        current = cls._default_sink_name(cls._remaining(deadline))
        if current not in {SPATIAL_NODE_NAME, previous}:
            # The user selected another sink while spatial audio was active.
            return
        nodes = cls._pipewire_nodes(cls._remaining(deadline))
        if previous not in nodes:
            raise SpatialError(f"previous default sink is unavailable: {previous}")
        cls._set_default(nodes[previous], deadline)
        cls._wait_for_default(previous, deadline)
